### ISSUE TITLE
`snapshot!` function occassionally raises `TypeError` exception

### ISSUE THREAD

**Issue by gstokkink** [pawurb/pg-locks-monitor#2]
Hi Pawel,

First of all, thank you for your hard work on this very useful gem. I have currently got the locks monitor running on our production services (as a periodic job), and noticed that sometimes the `snapshot!` function raises a `TypeError` exception with the message `TypeError: no implicit conversion of nil into String`. The error is caused by [this](https://github.com/pawurb/pg-locks-monitor/blob/main/lib/pg-locks-monitor.rb#L13) bit of code:

```
(ActiveSupport::Duration.parse(lock.fetch("age")).to_f * 1000) > configuration.locks_min_duration_ms
```

Apparently `lock.fetch("age")` can sometimes return `nil`, which results in `ActiveSupport::Duration.parse` raising the aforementioned `TypeError`. Do you have any idea how this value can be `nil`?

In case it matters, we are running PostgreSQL 16.3 on Amazon RDS. We run Rails 7.1.3 in combination with Ruby 3.3.4. Let me know if you need any more details.

Thanks,

Gerjan

**Comment by gstokkink** [comment]
Possibly related, but I also noticed we often receive lock notification of the following form:

```
{
    "pid": 5831,
    "relname": null,
    "transactionid": null,
    "granted": true,
    "mode": "ExclusiveLock",
    "query_snippet": "/action='autocomplete',database='ebdb',namespaced_controller='searches',request_id='19433985-bc37-46d6-8aee-0790c494255e'/ SELECT \"cities\".\"id\", \"cities\".\"tmp_name\", \"cities\".\"created_at\", \"cities\".\"updated_at\", \"cities\".\"country_code\", \"cities\".\"organization_id\", \"cities\".\"name_i18n\", \"cities\".\"user_id\", \"cities\".\"pending_review\" FROM \"cities\" WHERE \"cities\".\"id\" = 544 LIMIT 1",
    "age": "PT0.632064S",
    "application": "puma: cluster worker 1: 10 [pms]"
  }
```

Here you may notice that both `relname` and `transactionid` are `null`, which is surprising to me. It seems to only be locks of the type `ExclusiveLock` for which this happens.

**Comment by pawurb** [comment]
@gstokkink thanks for reporting! I've just released 0.1.2 which should resolve the issue with `nil` age by excluding these locks. 

As for missing rel names etc. it's not something we can influence because this data comes straight from pg. Optionally you can implement a custom `notifier_class` to exclude locks based on missing data.

Please reopen if something will still not be clear.

**Comment by pawurb** [comment]
Yeah, providing some customizable filter query could be useful. I'll think about it.

**Comment by pawurb** [comment]
@gstokkink please check out 0.2.0. It adds `locks_filter_proc` and `blocking_filter_proc` config. It should resolve your issue better than custom notifier.

**Comment by gstokkink** [comment]
@pawurb thanks for the quick follow-up! 👍

**Comment by gstokkink** [comment]
@pawurb just to follow up, I've looked a bit more closely into how it could be that `ExclusiveLock` locks were being reported for which `relname` is `null`. Through https://www.postgresql.org/message-id/20060223150529.GA18351%40winnie.fuhr.org I discovered this bit at https://www.postgresql.org/docs/16/view-pg-locks.html:

```
Throughout running a transaction, a server process holds an exclusive lock on the transaction's virtual transaction ID. If a permanent ID is assigned to the transaction (which normally happens only if the transaction changes the state of the database), it also holds an exclusive lock on the transaction's permanent transaction ID until it ends. When a process finds it necessary to wait specifically for another transaction to end, it does so by attempting to acquire share lock on the other transaction's ID (either virtual or permanent ID depending on the situation). That will succeed only when the other transaction terminates and releases its locks.
```

Sure enough, if I create an advisory lock and run `pg_locks`, I get the following:

```
  locktype  | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction |  pid  |      mode       | granted | fastpath | waitstart
------------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+-------+-----------------+---------+----------+-----------
 virtualxid |          |          |      |       | 3/400214   |               |         |       |          | 3/400214           | 46309 | ExclusiveLock   | t       | t        |
 relation   |  1480709 |    12073 |      |       |            |               |         |       |          | 7/173947           |   559 | AccessShareLock | t       | t        |
 virtualxid |          |          |      |       | 7/173947   |               |         |       |          | 7/173947           |   559 | ExclusiveLock   | t       | t        |
 advisory   |  1480709 |          |      |       |            |               |       0 |    10 |        1 | 3/400214           | 46309 | ExclusiveLock   | t       | f        |
(4 rows)
```

Clearly, these `virtualxid` locks are pretty useless (at least for my use cases). However, I cannot filter these locks out, as `locktype` (nor `database`, which could also be used to filter them out, as it's `null` for such locks) is not exposed through `RailsPgExtras.locks` or `RailsPgExtras.blocking`. Would you consider extending that gem to also include the `locktype` (or `database`)? 

By the way, it might even be a good idea to filter out the `virtualxid` locks by default. See what happens when I run `RailsPgExtras.locks` with a single advisory lock present:

```
DEVELOPMENT [16] irb(main)> RailsPgExtras.locks(in_format: :hash)
=>
[{"pid"=>46309, "relname"=>nil, "transactionid"=>nil, "granted"=>true, "mode"=>"ExclusiveLock", "query_snippet"=>"SELECT pg_advisory_xact_lock(10);", "age"=>"PT10M12.200077S", "application"=>"psql"},
 {"pid"=>46309, "relname"=>nil, "transactionid"=>nil, "granted"=>true, "mode"=>"ExclusiveLock", "query_snippet"=>"SELECT pg_advisory_xact_lock(10);", "age"=>"PT10M12.200077S", "application"=>"psql"}]
```

That is, the virtual transaction lock is included as well. What do you think? Thanks for your time in advance!

**Comment by pawurb** [comment]
@gstokkink I've just released https://github.com/pawurb/ruby-pg-extras/commit/069cf7bb38c7b323ae7a331b6205b7d57be2d8a4 to gem's core dependency. It adds `database` and `locktype` to locks info. For now I'd prefer not to exclude locks because it might confuse other users. Does that help?

**Comment by gstokkink** [comment]
@pawurb thanks, I'll filter these locks out by myself then 👍
