### ISSUE TITLE
Require `ruby-pg-extras` gem

### ISSUE THREAD

**Issue by aliismayilov** [pawurb/pg-locks-monitor#4]
`ruby-pg-extras` is listed as a dependency, but without it being required before the following line:
https://github.com/pawurb/pg-locks-monitor/blob/11a95ca53af5a5f477eae0978830fe3329cf167d/lib/pg-locks-monitor.rb#L8

you get the following error:
```
uninitialized constant PgLocksMonitor::RubyPgExtras (NameError)

    locks = RubyPgExtras.locks(
            ^^^^^^^^^^^^
```

**Comment by pawurb** [comment]
Sorry 😅 try `0.2.2`.
